# Generated by Django 2.1.5 on 2019-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todotask_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
