# Generated by Django 2.1.5 on 2019-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20190619_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Status',
            field=models.CharField(choices=[('I', 'Inprogress'), ('C', 'Completed'), ('P', 'Pending')], max_length=1),
        ),
    ]
