# Generated by Django 2.1.5 on 2019-06-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20190619_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
    ]
