# Generated by Django 2.1.5 on 2019-06-19 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20190619_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Modified_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_task_dates_times',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 9, 53, 13, 866201, tzinfo=utc)),
        ),
    ]
